import type { GitPageData } from "../../types/git";

export const mockGitData: GitPageData = {
  repositoryName: "Capstone-Server",
  stats: {
    commits: 8,
    connected: 4,
    disconnected: 4,
  },
  commits: [
    {
      id: "1",
      hash: "a13f9c2",
      message: "feat: 마이페이지 API 구현",
      decisionText: "마이페이지 기능 범위 확정",
      decisionType: "success" as const,
      authorName: "김준용",
      dateText: "2025.12.31 14:23",
      changesAdded: 234,
      changesRemoved: 12,
    },
    {
      id: "2",
      hash: "a13f9c2",
      message: "feat: 마이페이지 API 구현",
      decisionText: "마이페이지 기능 범위 확정",
      decisionType: "success" as const,
      authorName: "김준용",
      dateText: "2025.12.31 14:23",
      changesAdded: 234,
      changesRemoved: 12,
    },
    {
      id: "3",
      hash: "a13f9c2",
      message: "feat: 마이페이지 API 구현",
      decisionText: "",
      decisionType: "neutral" as const,
      authorName: "김준용",
      dateText: "2025.12.31 14:23",
      changesAdded: 234,
      changesRemoved: 12,
    },
    {
      id: "4",
      hash: "a13f9c2",
      message: "feat: 세션 저장소 인터페이스 분리",
      decisionText: "Redis 키 정책 변경",
      decisionType: "warning" as const,
      authorName: "김준용",
      dateText: "2025.12.31 14:23",
      changesAdded: 234,
      changesRemoved: 12,
    },
    {
      id: "5",
      hash: "a13f9c2",
      message: "feat: 유저 프로필 컴포넌트 구현",
      decisionText: "마이페이지 기능 범위 확정",
      decisionType: "success" as const,
      authorName: "김준용",
      dateText: "2025.12.31 14:23",
      changesAdded: 234,
      changesRemoved: 12,
    },
    {
      id: "6",
      hash: "a13f9c2",
      message: "refactor: 코드 리팩토링",
      decisionText: "",
      decisionType: "neutral" as const,
      authorName: "김준용",
      dateText: "2025.12.31 14:23",
      changesAdded: 234,
      changesRemoved: 12,
    },
  ],
};
